name: Create a comment on new issue
on:
 issues:
  types: [opened]
jobs:
 comment-with-actions:
  runs-on: ubuntu-latest
  steps:
   - name: "dump github context"
     run: echo '${{ toJSON(github.event) }}' | jq
     shell: bash
   - name: Create comment
     uses: peter-evans/create-or-update-comment@v4
     with:
      token: ${{ secrets.GH_PAT }}
      issue-number: ${{github.event.issue.number }}
      body: |
       This is a multi-line test comment
       - With GitHub **Markdown** :sparkles:
       - Created by [create-or-update-comment][1]

       [1]: https://github.com/peter-evans/create-or-update-comment
      reactions: '+1'
      
 comment-with-api:
  runs-on: ubuntu-latest
  steps:
   - name: Create comment with API
     run: |
      gh api -X POST \
       https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments\
       -f body='
       Comment but from API not from actions
       '
     env: 
      GH_TOKEN: ${{ secrets.GH_PAT }}
      ORGANIZATION: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.event.repository.name }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
 
